blank_issues_enabled: false
contact_links:
  - name: 项目群聊
    url: https://openai.justsong.cn/
    about: 演示站首页有官方群聊信息
  - name: 赞赏支持
    url: https://iamazing.cn/page/reward
    about: 请作者喝杯咖啡，以激励作者持续开发
  - name: 付费部署或定制功能
    url: https://openai.justsong.cn/
    about: 加群后联系群主
